### ISSUE TITLE
Usage of travis-ci 

### ISSUE THREAD

**Issue by andygill** [ku-fpg/blackboard#15]
Have someone rework our .travis.yml files to work better
- Caching of packages (for example natural-transformation)
- I do not know how to pre-load alex and happy (for example, the old-style sudo script in hermit)

The hermit-shell package was broken because when it tried to build hermit, there was no alex.

**Comment by RyanGlScott** [comment]
I've already replaced most of the `.travis.yml` files with ones that do implement caching of packages (assuming that a new version of a dependency hadn't been uploaded to Hackage since the last build). [Here's an example](https://github.com/ku-fpg/hermit/blob/906ccbd81855aefd71f2f2bc9339ac0dddc16333/.travis.yml#L47).

You can install prebuilt versions of `alex`/`happy` from hvr's Ubuntu PPA for GHC. For example, `hermit` [already does this](https://github.com/ku-fpg/hermit/blob/906ccbd81855aefd71f2f2bc9339ac0dddc16333/.travis.yml#L18).

I haven't updated `hermit-shell` yet because it requires manually `git clone-`ing two packages and installing them before doing anything else. I haven't found a good way to getting Travis to cache things besides the stuff that's installed when you run `cabal install --only-dependencies --enable-tests` (and you can't just stick other packages in with that command, `--enable-tests` would attempt to transitively build _their_ dependencies... it's a mess.)

**Comment by andygill** [comment]
The real problem is hermit-shell.  Now, its taking to long to _start_ to rebuild, because it needs the old system setup. Sigh.

**Comment by RyanGlScott** [comment]
If you're willing to try something a bit different, there exist `.travis.yml` generators that use `stack` instead of `cabal-install`. The advantage is that you can specify:

``` yaml
packages:
- '.'
- location:
    git: git@github.com:ku-fpg/hermit
    commit: 906ccbd81855aefd71f2f2bc9339ac0dddc16333
  extra-dep: true
- location:
    git: git@github.com:ku-fpg/remote-json
    commit: 2ca185cf2e19437c583b5e67e4e55e4ed8093454
  extra-dep: true
```

In `stack.yaml` and cache everything, including `hermit` and `remote-json`.

The downside to using `stack` is that you may have to fiddle with the `extra-deps` if you require something that isn't in a Stackage LTS or nightly (especially if you're using GHC HEAD). But it should be possible.
